[package]
name = "simple-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
lite-graphics = { path = "lite-graphics", default-features = false }

[target.'cfg(all(unix, not(any(target_os = "redox", target_family = "wasm", target_os = "android", target_os = "ios", target_os = "macos"))))'.dependencies]
x11rb = { version = "0.13", features = ["image"] }
wayland-client = "0.31"
wayland-protocols = { version = "0.32", features = ["client"] }
raw-window-handle = "0.6"
nix = { version = "0.29", features = ["mman", "fs"] }

[target.'cfg(target_os = "windows")'.dependencies]
windows = "0.59"

[workspace]
members = ["./lite-graphics"]
